import Panel from "../(components)/Panel";
import { CgCommunity, CgLockUnlock } from "react-icons/cg";
import { MdDiversity2, MdOutlineSecurity } from "react-icons/md";
import { CiBitcoin } from "react-icons/ci";

export const metadata = {
  title: "Zipcoin - Why Us",
  description: "Generated by create next app",
};

function About() {
  const reasons = [
    {
      title: "Unlock financial growth with cryptocurrencies.",
      icon: <CgLockUnlock />,
    },
    {
      title: "Diversify your portfolio with digital assets.",
      icon: <MdDiversity2 />,
    },
    {
      title: "Seamlessly trade and manage cryptocurrencies.",
      icon: <CiBitcoin />,
    },
    {
      title: "Trust our robust security measures.",
      icon: <MdOutlineSecurity />,
    },
    {
      title: "Join a thriving community of crypto enthusiasts.",
      icon: <CgCommunity />,
    },
  ];

  const reasonsList = reasons.map((reason) => {
    return (
      <Panel
        key={reason.title}
        className="hover:-translate-y-2 hover:shadow-xl hover:shadow-logo"
      >
        <div>{reason.icon}</div>
        <div className="p-5">{reason.title}</div>
      </Panel>
    );
  });

  return (
    <div className="flex flex-col justify-center h-center items-center py-8">
      <h1
        className="uppercase items-center 
      gap-4 flex flex-col text-7xl p-10
       bg-gradient-to-r from-burgundy to-logo text-transparent bg-clip-text"
      >
        Why you should <div>join us</div>
      </h1>
      <div className="flex flex-col gap-8 my-4">{reasonsList}</div>
    </div>
  );
}

export default About;
