import "./globals.css";
import { Ubuntu } from "next/font/google";
import NavBar from "./NavBar";
import Footer from "../../Footer";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--font-ubuntu",
  weight: "400",
});

export const metadata = {
  title: "Zipcoin - Buy Bitcoin and Cryptocurrencies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-b from-forest-green to-pine-green ${ubuntu.variable} font-sans`}
      >
        <NavBar />
        <div className="flex flex-col sm:min-h-screen pt-28">{children}</div>
        <div>
        <Footer />
        </div>
      </body>
    </html>
  );
}
