import Hero from "../(components)/Hero";
import Button from "../(components)/Button";

export const metadata = {
  title: "Zipcoin - Register",
  description: "Generated by create next app",
};

export default function RegisterPage() {
  return (
    <>
      <Hero />
      <div className="p-4 sm:p-10 sm:my-5">
        <div className="p-4 sm:p-10 flex justify-center">
          <div className="bg-logo p-20 rounded-md sm:text-right">
            <form className="grid grid-cols-1 gap-4">
                <div className="mb-4">
                <label className="p-2">ِE-mail</label>
              <input
                type="email"
                placeholder="E-mail address"
                className="form-input px-4 py-3 rounded-md"
              />
              </div>
              <div className="mb-4">
              <label className="px-2">Password</label>
              <input
                type="password"
                placeholder="Password"
                className="form-input px-4 py-3 rounded-md"
              />
              </div>
              <div className="mb-4">
              <label className=" px-2">Confirm Password</label>
              <input
                type="password"
                placeholder="Confirm Password"
                className="form-input px-4 py-3 rounded-md"
              />
              </div>
              <div className="flex justify-center">
                <Button register className="border border-black">SUBMIT</Button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}
